# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  dockerId: 'doanha1982'
  pswd: 'nguyenthithanhha'
  imageName: 'aspwebcorewithdocker'

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) ./AspWebCoreWithDocker
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)

